name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0
  
  #dateFormat
  intl: ^0.19.0

  #make request to api
  retrofit: ^4.1.0 
  
  #chached image 
  cached_network_image: ^3.2.0

  #api request & response
  dio: ^5.4.1

  # encryption
  crypto: ^3.0.3
  encrypt: ^5.0.3

  # model creation
  json_annotation: ^4.8.1

  #environment-specific
  flutter_dotenv: ^5.1.0


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  retrofit_generator: ^8.1.0
  json_serializable: ^6.6.0
  build_runner: ^2.2.0


  

flutter:
  assets:
    - .env_dev
  uses-material-design: true

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
